sudo: required
language: generic
services:
  - dockerfile

before_install:
  - docker build -t temmix/reactx-docker -f Dockerfile.dev .

script:
  - docker run -e CI=true temmix/reactx-docker npm run test  